### ISSUE TITLE
gulp watch crashes when folder deleted

### ISSUE THREAD

**Issue by theJuddson** [ngbolt/ng-bolt#22]
If a watched folder is deleted while bolt run is running, it crashes with the error: 

```
events.js:160
      throw er; // Unhandled 'error' event
      ^
Error: Error watching file for changes: EPERM
    at exports._errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
```

We need to evaluate our gulp watch tasks to see if we can respond to deleted folders more gracefully.

**Comment by SierraS** [comment]
So a temporary fix to this is to delete the contents of the folder individually since watch watches the folder's contents but not the folder entry. I'm still working on a way to delete the entry without the whole thing crashing, but I thought I'd put this out there if anyone needs an immediate solution.

**Comment by SierraS** [comment]
Oops, didn't mean to close.
